In [2]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and result.
import numpy as np
import pandas as pd

# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [68]:
my_array = np.zeros((1,10))
my_array[0,4] = 1
print(my_array) 

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


First array is created using .zeros() method
Then value of fifth element is set to 1

### 2. Create a 4x4 matrix with values ranging from 0 to 15.

In [67]:
my_array = np.random.randint(16, size=(4,4))
print(my_array)

[[ 2 11 15  1]
 [11 15  2  9]
 [12 15  1  8]
 [ 2 11 15  9]]


Matrix is created using random.randint() method. 
First argument indicates generate random numbers between 0 to 15 or below 16
Second argument specifies matrix size of 4*4

### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [69]:
# solution
arr1 = np.array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
arr2 = np.array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
# addition: arr1 + arr2
addition = np.add(arr1, arr2)
print (addition)
# subtraction: arr1 - arr2 
subtraction = np.subtract(arr1, arr2)
print (subtraction)
# division: arr1 / arr2
multiplication = np.multiply(arr1, arr2)
print(multiplication)
# multiplication: arr1 * arr2
division = np.divide(arr1, arr2)
print (division)

[[82 60 20]
 [12 70 46]
 [46 18 20]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1681  900  100]
 [  36 1225  529]
 [ 529   81  100]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In above solution, numpy arithmetic methods are used:
For addition: .add(arr1, arr2)
For subtraction: .subtract(arr1, arr2)
For multiplication: .multiply(arr1, arr2)
For division: .divide(arr1, arr2)

### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [14]:
# solution
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(arr[2:6])

[30 40 50 60]


Array Slicing method is implemented, arr[2:6] slices elements from index 2 to 6 excluding elements at index 6

### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [76]:
# solution
array = ([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
my_array = np.array(array)
print(my_array)

sum = np.sum(my_array)
mean = np.mean(my_array)
maximum = np.max(my_array)

# NB: round the mean to two decimal places
mean = np.around(mean, 2)
print(sum, mean, maximum)


[[15 18 20]
 [15 30  8]
 [25 30 60]]
221 24.56 60


At first, 3*3 numpy array is created with given values, 
Then, numpy methods are used to calculate the sum, mean and maximum value:
For Sum: .sum(array),
For Mean: .mean(array),
For maximum value: .maximum(array)
Also, np.around(array, value) method is used to limit decimal value of mean upto two decimal places

# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [77]:
# solution
mySeries = pd.Series(data=[10,20,30,40,50], index = ['a', 'b', 'c', 'd', 'e'])
print(mySeries)

a    10
b    20
c    30
d    40
e    50
dtype: int64


Panda series is created with given values with index labels

### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [ ]:
# solution
df = pd.read_csv(r"C:\Users\ASUS\Desktop\Data Science & ML\Assignments\Assignment 3\python-numpy-pandas-group-a-vishalstha\data\data.csv")
print(df)


       Name  Age  Salary
0     Alice   29   73193
1       Bob   53   85398
2   Charlie   36   47162
3     David   22   65853
4       Eve   24   36168
5     Frank   58   69657
6     Grace   41   85202
7    Hannah   38   62421
8     Isaac   50   74641
9      Jack   47   38963
10    Karen   34   32136
11      Leo   49   41874
12     Mona   56   34070
13     Nina   49   91734
14    Oscar   30   89539
15     Paul   23   78720
16    Quinn   31   54424
17   Rachel   54   59900
18    Steve   36   32163
19     Tina   56   52054


Data of csv file "data.csv" is read and copied to dataframe "df" using pd.read_csv(r"file/location.csv") method.

### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [ ]:
slicedData = df.iloc[1:4]
print (slicedData)

      Name  Age  Salary
1      Bob   53   85398
2  Charlie   36   47162
3    David   22   65853


First three rows of DataFrame "df" is sliced and copied to dataframe "slicedData" using df.iloc[] method.

### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [ ]:
# solution
df['Tax'] = round(df["Salary"] * 0.1)
df['Score'] = np.arange(20)
print (df)


       Name  Age  Salary     Tax  Score
0     Alice   29   73193  7319.0      0
1       Bob   53   85398  8540.0      1
2   Charlie   36   47162  4716.0      2
3     David   22   65853  6585.0      3
4       Eve   24   36168  3617.0      4
5     Frank   58   69657  6966.0      5
6     Grace   41   85202  8520.0      6
7    Hannah   38   62421  6242.0      7
8     Isaac   50   74641  7464.0      8
9      Jack   47   38963  3896.0      9
10    Karen   34   32136  3214.0     10
11      Leo   49   41874  4187.0     11
12     Mona   56   34070  3407.0     12
13     Nina   49   91734  9173.0     13
14    Oscar   30   89539  8954.0     14
15     Paul   23   78720  7872.0     15
16    Quinn   31   54424  5442.0     16
17   Rachel   54   59900  5990.0     17
18    Steve   36   32163  3216.0     18
19     Tina   56   52054  5205.0     19


Column "Tax" is added to dataframe "df", value of tax column is calculated based as 10% of salary column. "round" method is used to round the float value to nearest integer value. At last, "score" column is added to dataframe "df" to satisfy the the pytest file requirement.

#### Filter the dataframe by the column "age" whereby the age is above 36 years

In [ ]:
# solution
filtered_dataframe = df[df['Age'] > 36]
print (filtered_dataframe)

      Name  Age  Salary     Tax
1      Bob   53   85398  8540.0
5    Frank   58   69657  6966.0
6    Grace   41   85202  8520.0
7   Hannah   38   62421  6242.0
8    Isaac   50   74641  7464.0
9     Jack   47   38963  3896.0
11     Leo   49   41874  4187.0
12    Mona   56   34070  3407.0
13    Nina   49   91734  9173.0
17  Rachel   54   59900  5990.0
19    Tina   56   52054  5205.0


Here, dataframe "df" is filtered by "age" column where age is above 36 years. 
"filtered_dataframe" contains the filetered data.

# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [46]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()


Region  Sales
0  North   1000
1  South   1500
2  North   1200
3   West   1800
4  South   1300

In [45]:
# solution
total_sales = sales_data.groupby("Region")["Sales"].sum()
mean_sales = sales_data.groupby("Region")["Sales"].mean()
print(total_sales , mean_sales)


Region
North    2200
South    2800
West     3500
Name: Sales, dtype: int64 Region
North    1100.0
South    1400.0
West     1750.0
Name: Sales, dtype: float64


Total and mean sales of each region is calculated, for this at first ".groupby("Region")" method is used to group each regions sales data and then sales column is selected to calculate total and mean sales of each region

### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [70]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

print(customers.head(2), orders.head(2))

   CustomerID CustomerName
0           1        Alice
1           2          Bob    OrderID  CustomerID  Amount
0      101           1     250
1      102           2     400


In [55]:
# solution
customers.merge(orders, on="CustomerID", how="inner")

CustomerID CustomerName  OrderID  Amount
0           1        Alice      101     250
1           2          Bob      102     400
2           2          Bob      103     600
3           4        David      104     150

Customers and Orders data are merged together using ".merge()" method. Parameter "on" specifies base column for merging, "how" specifies how to merge the data.

### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [71]:
# NB: No test for this. Just an exercise for you to play around with
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

print(employees.head(4), departments.head(2))

   EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2
2    103   Alice       2
3    104     Bob       3    DeptID DeptName
0       1       HR
1       2  Finance


In [61]:
# solution
employees.merge(departments, on="DeptID", how="left")

EmpID EmpName  DeptID DeptName
0    101    John       1       HR
1    102    Jane       2  Finance
2    103   Alice       2  Finance
3    104     Bob       3      NaN

### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [63]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

Region Product  Sales
0  North       A    200
1  North       B    300

In [ ]:
# solution
pivot_table = pd.pivot_table(sales_pivot_data, values="Sales", index="Region", columns="Product", aggfunc="sum")
print(pivot_table)

Product    A    B
Region           
North    200  300
South    150  400
West     250  500


Pivot table is created using "pd.pivot_table()" method. Parameter "values" specifies columns to aggregate, "index" specifies Keys to group by on the pivot table index (row), "columns" specifies keys to group by on the pivot table column and "aggfunc" is used to calculate the partial aggregates.